[helloworld]
description="Just hello world"
version="1.0"
arch=["x86_64"]
deps=[]

[nano]
description="A small text editor"
version="8.6"
arch=["x86_64"]
deps=[]

[fastfetch]
description="A maintained, feature-rich and performance oriented, neofetch like system information tool"
version="2.50.2"
arch=["x86_64"]
deps=[]

[nachosconsole_old]
description = "Old Nachos Console https://github.com/nachosteam/nachos-console"
version = "commit_11b911e"
arch = ["x86_64"]
deps = []
